# syntax=docker/dockerfile:latest

ARG BASE_IMAGE

FROM --platform=$TARGETPLATFORM ${BASE_IMAGE}

# Install necessary packages
RUN apt-get update && apt-get install -y curl dpkg

# print architecture
RUN dpkg --print-architecture

# Download and install the app
ARG LOC=https://packages.zus.network/deb_install.sh
RUN set -e; \
    curl -sL ${LOC} | sudo bash

# Check the app version
CMD ["zbox", "version"]

