FROM --platform=$TARGETPLATFORM golang:1.21 AS build
ARG VERSION
WORKDIR /src
COPY go.mod go.sum .
RUN go mod download
COPY . .
RUN go env
RUN CGO_ENABLED=1 go build -x -v -tags bn256 -ldflags "-X main.VersionStr=${VERSION}" -o /zbox .
