name: build-linux
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Install
      run: make install

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: zbox-cli
        path: zbox
        retention-days: 5