name: build-cli
on: [push, pull_request]
jobs:
  build-linux:
    name: Build-linux
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Install
      run: make install

    - name: zip release
      run: tar -czvf zbox-linux.tar.gz ./zbox

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: zbox-linux.tar.gz
        tag: 'v0.0.0-beta'
        overwrite: true
        file_glob: true

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: zbox-cli-linux
        path: zbox
        retention-days: 5
  build-windows:
    name: Build-windows
    runs-on: windows-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Install
      run: make install
    
    - name: rename zbox
      run: |
        copy zbox zbox.exe
        7z a zbox-windows.zip zbox.exe

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: zbox-windows.zip
        tag: 'v0.0.0-beta'
        overwrite: true
        file_glob: true

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: zbox-cli-windows
        path: zbox
        retention-days: 5
  build-macos:
    name: Build-macos
    runs-on: macos-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Install
      run: make install
    - name: zip release
      run: tar -czvf zbox-macos.tar.gz ./zbox

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: zbox-macos.tar.gz
        tag: 'v0.0.0-beta'
        overwrite: true
        file_glob: true

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: zbox-cli-macos
        path: zbox
        retention-days: 5