name: build-cli
on: [push, pull_request]
jobs:
  build-linux:
    name: Build-linux
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Install
      run: make install

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: zbox
        asset_name: zbox-linux
        tag: 'v0.0.0-beta'
        overwrite: true
        file_glob: true

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: zbox-cli-linux
        path: zbox
        retention-days: 5
  build-windows:
    name: Build-windows
    runs-on: windows-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Install
      run: make install
    

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: zbox
        asset_name: zbox.exe
        tag: 'v0.0.0-beta'
        overwrite: true
        file_glob: true

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: zbox-cli-windows
        path: zbox
        retention-days: 5
  build-mac:
    name: Build-mac
    runs-on: macos-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Install
      run: make install

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: zbox-cli-macos
        path: zbox
        retention-days: 5