name: build-zbox
on:
  push:
    branches:
      - master
      - dev
    tags:
      - 'v*.*.*'

  pull_request:
    branches:
      - master
      - production
jobs:
  build-linux:
    name: Build-linux
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set GITHUB_ENV
      run: |
        echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

        if [[ "${{github.base_ref}}" == "master" || "${{github.ref}}" == "refs/heads/master" ]]; then
          echo "TAG=v0.0.0-master" >> $GITHUB_ENV
        elif  [[ "${{github.base_ref}}" == "dev" || "${{github.ref}}" == "refs/heads/dev" ]]; then
          echo "TAG=v0.0.0-dev" >> $GITHUB_ENV
        else
          echo "TAG=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
        fi

    - name: Install
      run: make install

    - name: Zip release
      run: tar -czvf zbox-linux.tar.gz ./zbox

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: zbox-linux.tar.gz
        tag: ${{ env.TAG }}
        overwrite: true
        file_glob: true

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: zbox-linux
        path: zbox
        retention-days: 5
  build-windows:
    name: Build-windows
    runs-on: windows-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: olegtarasov/get-tag@v2.1
      id: tagName
      with:
        tagRegex: "v(.*)"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.

    - name: Set GITHUB_ENV
      run: |
        IF ( "${{github.base_ref}}" -eq "master" -OR "${{github.ref}}" -eq "refs/heads/master" ){
          echo "TAG=v0.0.0-master" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        } ElseIf ( "${{github.base_ref}}" -eq "dev" -OR "${{github.ref}}" -eq "refs/heads/dev" ){
          echo "TAG=v0.0.0-dev" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        } ELSE {
          echo "TAG=$(echo ${GIT_TAG_NAME})" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        }

        echo  ${{ env.TAG }}
    
    - name: Install
      run: make install
    
    - name: Zip release
      run: |
        copy zbox zbox.exe
        7z a zbox-windows.zip zbox.exe

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: zbox-windows.zip
        tag: ${{ env.TAG }}
        overwrite: true
        file_glob: true

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: zbox-windows
        path: zbox
        retention-days: 5
  build-macos:
    name: Build-macos
    runs-on: macos-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set GITHUB_ENV
      run: |
        echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

        if [[ "${{github.base_ref}}" == "master" || "${{github.ref}}" == "refs/heads/master" ]]; then
          echo "TAG=v0.0.0-master" >> $GITHUB_ENV
        elif  [[ "${{github.base_ref}}" == "dev" || "${{github.ref}}" == "refs/heads/dev" ]]; then
          echo "TAG=v0.0.0-dev" >> $GITHUB_ENV
        else
          echo "TAG=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
        fi

    - name: Install
      run: make install
    - name: Zip release
      run: tar -czvf zbox-macos.tar.gz ./zbox

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: zbox-macos.tar.gz
        tag: ${{ env.TAG }}
        overwrite: true
        file_glob: true

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: zbox-macos
        path: zbox
        retention-days: 5