name: BUILD-ZBOXCLI

on:
  workflow_dispatch:
    inputs:
      fixed_tag:
        description: 'Type yes For Building With Tag v0.0.0 from master & v1.1.1 from staging'
        default: 'no'
        required: true
      version_tag:
        description: 'Input Tag Example - v1.2.2'
        required: true
env:
  GITHUB_TOKEN: ${{ secrets.GOSDK }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Install
      run: make install

    - name: Get Branch
      id: get_version
      run: |
        VERSION=$(echo ${GITHUB_REF#refs/heads/}) 
        echo ::set-output name=TAG::${VERSION}
        
    - name: Create Release for Fixed v1.1.1
      id: create_release_v1_1_1
      if: github.event.inputs.fixed_tag == 'yes' && steps.get_version.outputs.TAG == 'staging'
      uses: zendesk/action-create-release@v1
      with:
        tag_name: v1.1.1
        release_name: v1.1.1
        draft: false
        prerelease: false

    - name: Create Release for Fixed v0.0.0
      id: create_release_v0_0_0
      if: github.event.inputs.fixed_tag == 'yes' && steps.get_version.outputs.TAG == 'master'
      uses: zendesk/action-create-release@v1
      with:
        tag_name: v0.0.0
        release_name: v0.0.0
        draft: false
        prerelease: false

    - name: Create Release for Input Tag
      id: create_release_fix
      uses: zendesk/action-create-release@v1 
      with:
        tag_name: ${{ github.event.inputs.version_tag }}
        release_name: ${{ github.event.inputs.version_tag }}
        draft: false
        prerelease: false